# Generated by Django 3.2.1 on 2022-02-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='useer',
            new_name='user',
        ),
    ]
